// Server-side opaque sync storage. The server authenticates accounts but never receives
// notes, labels, images, tombstones, or any decryptable user payload.
import { existsSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from 'fs';
import { join } from 'path';

/** `slot` is an opaque, keyed identifier generated by the client for a logical record.
 * It lets the relay replace an old ciphertext without learning whether it is a note, image, etc. */
export type EncryptedEnvelope = { seq: number; id: string; ciphertext: string; slot?: string };
export interface SyncUser {
	credentialHash: string;
	envelopes: EncryptedEnvelope[];
	/** Monotonic sequence survives slot replacement so devices never miss an update. */
	nextSeq?: number;
	updatedAt: number;
}
export interface SyncData { [accountId: string]: SyncUser; }

const DATA_DIR = 'sync-data';
const DATA_FILE = join(DATA_DIR, 'users.json');
function ensureDataFile(): void {
	if (!existsSync(DATA_DIR)) mkdirSync(DATA_DIR, { recursive: true });
	if (!existsSync(DATA_FILE)) writeFileSync(DATA_FILE, '{}\n', { encoding: 'utf-8', flag: 'wx' });
}

/** Removes legacy plaintext records the moment this privacy model is loaded. */
export function readSyncData(): SyncData {
	ensureDataFile();
	const parsed: unknown = JSON.parse(readFileSync(DATA_FILE, 'utf-8'));
	if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('Sync data file is not a JSON object');
	const data = parsed as Record<string, Record<string, unknown>>;
	let changed = false;
	for (const account of Object.values(data)) {
		if (!Array.isArray(account.envelopes)) { account.envelopes = []; changed = true; }
		const rawEnvelopes = account.envelopes as EncryptedEnvelope[];
		const slotted = rawEnvelopes.filter((envelope) => typeof envelope?.slot === 'string' && typeof envelope?.ciphertext === 'string');
		if (slotted.length !== rawEnvelopes.length) { account.envelopes = slotted; changed = true; }
		const maxSeq = Math.max(0, ...(slotted.map((envelope) => Number(envelope.seq) || 0)));
		if (!Number.isInteger(account.nextSeq) || Number(account.nextSeq) < maxSeq) {
			account.nextSeq = maxSeq;
			changed = true;
		}
		for (const field of ['syncCode', 'notes', 'labels', 'boards', 'tombstones', 'labelTombstones', 'boardTombstones']) {
			if (field in account) { delete account[field]; changed = true; }
		}
	}
	if (changed) writeSyncData(data as unknown as SyncData);
	return data as unknown as SyncData;
}
export function writeSyncData(data: SyncData): void {
	ensureDataFile();
	const temp = `${DATA_FILE}.${process.pid}.${Date.now()}.tmp`;
	try { writeFileSync(temp, `${JSON.stringify(data, null, 2)}\n`, 'utf-8'); renameSync(temp, DATA_FILE); }
	catch (err) { try { if (existsSync(temp)) unlinkSync(temp); } catch { /* best effort */ } throw err; }
}
